"""Model registry and core settings seed data."""

MODEL_SEED_ROWS = (
    {
        "provider": "ollama",
        "name": "qwen2.5:7b",
        "ollama_tag": "qwen2.5:7b",
        "api_model_id": None,
        "tier": "mid",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 1,
    },
    {
        "provider": "ollama",
        "name": "llama3.1:8b",
        "ollama_tag": "llama3.1:8b",
        "api_model_id": None,
        "tier": "mid",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 1,
    },
    {
        "provider": "ollama",
        "name": "gemma2:9b",
        "ollama_tag": "gemma2:9b",
        "api_model_id": None,
        "tier": "mid",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 1,
    },
    {
        "provider": "ollama",
        "name": "phi3:mini",
        "ollama_tag": "phi3:mini",
        "api_model_id": None,
        "tier": "low",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 1,
    },
    {
        "provider": "ollama",
        "name": "qwen2.5-coder:7b",
        "ollama_tag": "qwen2.5-coder:7b",
        "api_model_id": None,
        "tier": "mid",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 1,
    },
    {
        "provider": "ollama",
        "name": "mistral",
        "ollama_tag": "mistral",
        "api_model_id": None,
        "tier": "low",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 1,
    },
    {
        "provider": "anthropic",
        "name": "claude",
        "ollama_tag": None,
        "api_model_id": None,
        "tier": "high",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 0,
    },
    {
        "provider": "openai",
        "name": "gpt",
        "ollama_tag": None,
        "api_model_id": None,
        "tier": "high",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 0,
    },
    {
        "provider": "deepseek",
        "name": "deepseek-chat",
        "ollama_tag": None,
        "api_model_id": None,
        "tier": "mid",
        "input_cost_per_1k": 0.0,
        "output_cost_per_1k": 0.0,
        "enabled": 0,
    },
)

CORE_SETTINGS = {
    "fx_rate_usd_sek": "11.0",
    "complexity_tier_map": "1-2:low,3:mid,4-5:high",
    "router_default": "off",
    "router_enabled": "false",
    "cost_ceiling_sek": "50",
}
